второй блок
BulatKZN/Verstka-portfolio pull request #3
Opened 2020-12-06 20:46 UTC by BulatKZN

2020-12-07 09:21 UTC, IlgamGabdullin requested changes

2020-12-07 09:21 UTC, IlgamGabdullin commented on debug.log
> +[1204/214930.565:ERROR:directory_reader_win.cc(43)] FindFirstFile: ������� �� ������� ����� ��������� ����. (0x3)
че за лог файл?) 
почитай про .gitignore файл, внеси туда *.log

2020-12-07 09:21 UTC, IlgamGabdullin commented on style.css
> +.u-ta-center{
красава что понял удобство и используешь утилитки)

2020-12-07 09:21 UTC, IlgamGabdullin commented on style.css
> +
старайся следить за форматированием кода:
не оставляй лишние переносы строк, пробелы
и делай переносы строк между классами

2020-12-08 13:04 UTC, BulatKZN commented on style.css
> +
все поменял

2020-12-08 13:18 UTC, IlgamGabdullin commented on .gitignore
> +git status
че эт?)

2020-12-08 13:19 UTC, IlgamGabdullin commented on gitignore
> +debug.log
этче ?)

2020-12-13 08:55 UTC, IlgamGabdullin commented on style.css
> +    background-image: url(img/blog/bgc\ header.png);
пути лучше всегда указывать в кавычках
`url('img/blog/bgc\ header.png');`

2020-12-13 08:59 UTC, IlgamGabdullin commented on blog.html
> +    <title>Document</title>
тут можно менять название страницы 
это то что указывается в табах браузера

2020-12-13 09:02 UTC, IlgamGabdullin commented on style.css
> +.header-menu-nav-item:nth-child(4){
всегда имей в виду что элементов меню может стать больше
обычно они добавляются через cms, типа wordpress'а
и в твоем случае придется еще css менять - это плохо 
посмотри на :last-of-type

2020-12-13 09:03 UTC, BulatKZN commented on style.css
> +    background-image: url(img/blog/bgc\ header.png);
хорошо

2020-12-13 09:03 UTC, BulatKZN commented on blog.html
> +    <title>Document</title>
да понял

2020-12-13 09:21 UTC, merged